spring:
  kafka:
    bootstrap-servers: localhost:29092
    # default url for schema registry is localhost:8081
    schema.registry.url: http://localhost:8081
    consumer:
      group-id: my-group
#      # Configures the Spring Kafka ErrorHandlingDeserializer that delegates to the 'real' deserializers
#      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    properties:
#      # Delegate deserializers
#      spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
#      spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
      schema.registry.url: http://localhost:8081
#    producer:
#      group-id: my-group
#      # Configures the Spring Kafka ErrorHandlingDeserializer that delegates to the 'real' deserializers
#      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
topic: topic1
schema.registry.url: http://localhost:8081



